import React from "react";
import {
	Container,
	Grid,
	Divider,
	Typography,
	Card,
	CardContent,
} from "@mui/material";

const Experience = () => {
	return (
		<Container disableGutters sx={{ minWidth: "100%", height: 700 }}>
			<div style={{ textAlign: "center" }}>
				<Typography
					sx={{
						marginBottom: "-20px",
						paddingTop: "20px",
						fontSize: 20,
						height: 20,
						color: "white",
					}}
				>
					Experience
				</Typography>
			</div>
			<Grid
				container
				direction='column'
				justifyContent='flex-start'
				alignItems='center'
				spacing={5}
				sx={{ height: "100%", backgroundColor: "#181716", paddingTop: 10 }}
			>
				<Grid item sx={{ width: "50%" }}>
					<Card sx={{ backgroundColor: "#57504d" }}>
						<CardContent>
							<Typography sx={{ textDecoration: "underline" }}>
								February 2023 - Present - Undergraduate Research Assistant
							</Typography>
							<div style={{ paddingLeft: "20px" }}>
								<Typography>
									Developed interpersonal communication skills collaborating
									with peers to accomplish tasks.
								</Typography>
								<Typography>
									Developed real world coding skills using C#, Python, and
									Matlab to process images and data utilizing machine learning
									to predict future samples.
								</Typography>
								<Typography>
									Performed as a Software Engineer interpreting needs of Civil
									and Environmental Engineers working to write and explain code
									for projects.
								</Typography>
							</div>
						</CardContent>
					</Card>
				</Grid>
				<Grid item sx={{ width: "80%" }}>
					<Divider
						variant='middle'
						orientation='horizontal'
						sx={{ bgcolor: "#8A6240", borderBottomWidth: 2 }}
					/>
				</Grid>
				<Grid item sx={{ width: "50%" }}>
					<Card sx={{ backgroundColor: "#57504d" }}>
						<CardContent>
							<Typography sx={{ textDecoration: "underline" }}>
								May 2022 - October 2022 - Software/React Developer for Crimer
							</Typography>
							<div style={{ paddingLeft: "20px" }}>
								<Typography>
									Developed real world coding skills using React, React Native,
									Material UI, Node.js, JavaScript, and TypeScript in a
									competitive work environment while working on websites or apps
									like Gretna Live to organize a city's events and provide the
									citizens a place to view them.
								</Typography>
								<Typography>
									Learned to work in an AGILE environment with weekly SCRUM
									meetings.
								</Typography>
								<Typography>
									Collaborated with others to solve problems generated by time
									and contribution in the team and reach deadlines for real
									world projects.
								</Typography>
							</div>
						</CardContent>
					</Card>
				</Grid>
			</Grid>
		</Container>
	);
};

export default Experience;
